# Generated by Django 5.2 on 2025-10-03 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال یا غیرفعال؟')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='weblog/', verbose_name='عکس ها')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='weblog/', verbose_name='عکس ها')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='weblog/', verbose_name='عکس ها')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح کامل')),
                ('q1', models.TextField(blank=True, null=True, verbose_name='سوال 1')),
                ('a1', models.TextField(blank=True, null=True, verbose_name='جواب 1')),
                ('q2', models.TextField(blank=True, null=True, verbose_name='سوال 2')),
                ('a2', models.TextField(blank=True, null=True, verbose_name='جواب 2')),
                ('q3', models.TextField(blank=True, null=True, verbose_name='سوال 3')),
                ('a3', models.TextField(blank=True, null=True, verbose_name='جواب 3')),
                ('creator_img', models.ImageField(upload_to='weblog/creators/', verbose_name='عکس سازنده ')),
                ('creator_name', models.CharField(max_length=50, verbose_name='اسم سازتده')),
                ('creator_des', models.TextField(verbose_name='توضیح سازنده')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='url عنوان در ')),
                ('created_at', models.CharField(max_length=50, verbose_name='تاریخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال یا غیرفعال؟')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='weblog.category', verbose_name='کتگوری')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
