# Generated by Django 5.2 on 2025-10-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weblog',
            options={'verbose_name': 'وبلاگ', 'verbose_name_plural': 'وبلاگ'},
        ),
        migrations.AlterField(
            model_name='weblog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
