# Generated by Django 5.2 on 2025-10-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_alter_weblog_options_alter_weblog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
