# Generated by Django 5.2 on 2025-10-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='default-name', max_length=200, verbose_name='نام سایت')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='لوگو سایت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('address', models.CharField(max_length=50, verbose_name='ادرس')),
                ('domain_name', models.CharField(max_length=50, verbose_name='اسم دامنه')),
                ('github_link', models.URLField(verbose_name='لینک گیت هاب')),
                ('instagram_link', models.URLField(verbose_name='لینک اینستاگرام')),
                ('linkdin_link', models.URLField(verbose_name='لینک لینکدین')),
                ('copyright_text', models.CharField(default='default-copyright_text', max_length=50, verbose_name='متن کپی رایت')),
                ('is_main_setting', models.BooleanField(default=False, verbose_name='تنضیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
