# Generated by Django 5.2 on 2025-10-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_model',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='لوگو سایت'),
        ),
    ]
