# Generated by Django 5.2 on 2025-10-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_alter_site_model_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_model',
            name='copy',
            field=models.CharField(default='', max_length=50, verbose_name='متن کپی رایت لینک'),
        ),
        migrations.AddField(
            model_name='site_model',
            name='copy_url',
            field=models.URLField(default='', verbose_name='لینک کپی رایت'),
        ),
        migrations.AlterField(
            model_name='site_model',
            name='copyright_text',
            field=models.CharField(default='', max_length=50, verbose_name='متن کپی رایت'),
        ),
    ]
