# Generated by Django 5.2 on 2025-10-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل مشتری')),
                ('massage', models.TextField(max_length=300, verbose_name='پیام مشتری')),
                ('is_read_admin', models.BooleanField(default=False, verbose_name='خوانده شده/خوانده نشده')),
            ],
            options={
                'verbose_name': 'پبام',
                'verbose_name_plural': 'پبام ها',
            },
        ),
    ]
