# Generated by Django 5.2 on 2025-10-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_model',
        ),
    ]
