# Generated by Django 5.2 on 2025-10-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='وضعیت')),
                ('title_1_of_3', models.CharField(max_length=50, verbose_name='خط اول اسم')),
                ('title_2_of_3', models.CharField(max_length=50, verbose_name='خط دوم اسم')),
                ('descreption', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/ غیر فعال')),
            ],
            options={
                'verbose_name': 'تنظیمات خانه',
                'verbose_name_plural': ' تنظیمات خانه',
            },
        ),
        migrations.CreateModel(
            name='my_ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='مهارتت')),
                ('icon', models.CharField(default='default-icon', max_length=50, verbose_name='اسم مهارت به اینگلیسی برای ایکون')),
                ('percent', models.CharField(max_length=50, verbose_name='درصد بلدی شما')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال /غیر فعال')),
            ],
            options={
                'verbose_name': ' مهارت های من ',
                'verbose_name_plural': ' مهارت های من  ',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='خدمات که ارائه میدی')),
                ('projects', models.CharField(max_length=50, verbose_name='تعداد پروژه که انجام دادی')),
                ('icon', models.CharField(default='default-icon', max_length=50, verbose_name='اسم به اینگلیسی برای ایکون')),
                ('descreption', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('url', models.URLField(default='default-url', verbose_name='لینک برای بیشتر بخوانید')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال /غیر فعال')),
            ],
            options={
                'verbose_name': 'چه خدماتی ارائه می دهم؟',
                'verbose_name_plural': 'چه خدماتی ارائه می دهم؟',
            },
        ),
        migrations.CreateModel(
            name='work_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='سلام من ... هستم')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/ غیر فعال')),
            ],
            options={
                'verbose_name': 'حوزه کاری',
                'verbose_name_plural': 'حوزه کاری',
            },
        ),
    ]
