# Generated by Django 5.2 on 2025-10-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_model',
            name='status',
            field=models.CharField(default='default', max_length=50, verbose_name='وضعیت'),
        ),
    ]
