# Generated by Django 5.2 on 2025-10-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_model_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commet', models.CharField(max_length=300, verbose_name='متن کامنت ')),
                ('stars', models.CharField(max_length=50, verbose_name='تعداد ستاره')),
                ('image', models.ImageField(upload_to='comment/', verbose_name='عکس کامنت ')),
                ('name', models.CharField(max_length=50, verbose_name='اسم کامنت گذار')),
                ('fro', models.CharField(max_length=50, verbose_name='مشتری کامنت گذار')),
            ],
            options={
                'verbose_name': ' کامنت',
                'verbose_name_plural': ' کامنت ',
            },
        ),
    ]
