# Generated by Django 5.2 on 2025-10-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال /غیر فعال'),
        ),
    ]
