# Generated by Django 5.2 on 2025-10-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comments_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='stars',
            field=models.IntegerField(default=1, verbose_name='تعداد ستاره'),
        ),
    ]
