# Generated by Django 5.2 on 2025-10-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_comments_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_area',
            name='title',
            field=models.CharField(max_length=50, verbose_name='باکس مهارت'),
        ),
    ]
