# Generated by Django 5.2 on 2025-10-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_work_area_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_ability',
            name='icon_img',
            field=models.ImageField(blank=True, null=True, upload_to='iconlogo/', verbose_name='یا افضودن عکس'),
        ),
        migrations.AddField(
            model_name='services',
            name='icon_img',
            field=models.ImageField(blank=True, null=True, upload_to='iconlogo/', verbose_name='یا افضودن عکس'),
        ),
    ]
