# Generated by Django 5.2 on 2025-10-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_my_ability_icon_img_services_icon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_ability',
            name='icon',
            field=models.CharField(blank=True, default='default-icon', max_length=50, null=True, verbose_name='اسم مهارت به اینگلیسی برای ایکون'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(blank=True, default='default-icon', max_length=50, null=True, verbose_name='اسم به اینگلیسی برای ایکون'),
        ),
    ]
