# Generated by Django 5.2 on 2025-10-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='portfolio/', verbose_name='1عکس نمونه کار')),
                ('img2', models.ImageField(upload_to='portfolio/', verbose_name='2عکس نمونه کار')),
                ('img3', models.ImageField(upload_to='portfolio/', verbose_name='3عکس نمونه کار')),
                ('title', models.CharField(max_length=100, verbose_name='اسم')),
                ('type1', models.CharField(blank=True, max_length=100, null=True, verbose_name='با چیا پروژه رو زدی')),
                ('type2', models.CharField(blank=True, max_length=100, null=True, verbose_name='با چیا پروژه رو زدی')),
                ('type3', models.CharField(blank=True, max_length=100, null=True, verbose_name='با چیا پروژه رو زدی')),
                ('type4', models.CharField(blank=True, max_length=100, null=True, verbose_name='با چیا پروژه رو زدی')),
                ('customer', models.CharField(max_length=50, verbose_name='مشتری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح کامل')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='url عنوان در ')),
                ('url_github', models.URLField(blank=True, null=True, verbose_name='لینک گیت هاب پروژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال یا غیرفعال؟')),
            ],
            options={
                'verbose_name': ' نمونه کار ها',
                'verbose_name_plural': ' نمونه کار ها',
            },
        ),
    ]
