# Generated by Django 5.2 on 2025-10-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prot_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تایتل برای پلن ها')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال /غیر فعال')),
            ],
            options={
                'verbose_name': 'تایتل نمونه کار ها',
                'verbose_name_plural': 'تایتل نمونه کار ها',
            },
        ),
    ]
