# Generated by Django 5.2 on 2025-10-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_prot_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='img3',
        ),
    ]
